[project]
name = "tokenadapt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.12.0",
    "numpy>=1.20.0",
    "torch>=2.0.0",
    "tqdm>=4.60.0",
    "transformers>=4.30.0",
]
